apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dbUI.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dbUI.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbUI.name }}
        project-name: wca4z
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      #nodeSelector:
      #  nvidia.com/gpu.present: "{{ .Values.nodeSelector.gpu }}"
      volumes:
        - name: rag-akm-storage-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}



      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rag-milvus
            topologyKey: kubernetes.io/hostname



      containers:
        - name: db-app
          image: {{ .Values.dbUI.image }}
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: HUGGINGFACE_HUB_CACHE
              value: "/platform_storage/HF_HOME"
            - name: PATH
              value: "/usr/bin:/bin:/usr/local/bin"
          ports:
            - name: websocket
              containerPort: {{ .Values.dbUI.port }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Starting DB UI"
              git clone https://github.com/vpatz/rag-llm-gitops-bharatgen.git
              cd rag-llm-gitops-bharatgen/edu-rag-app
              git clone https://github.com/anoopkunchukuttan/indic_nlp_resources.git
              python3 ui/ui_ingest.py
          resources:
{{ toYaml .Values.dbUI.resources | indent 12 }}
          volumeMounts:
{{ toYaml .Values.commonVolumeMount.volumeMounts | indent 12 }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbUI.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.dbUI.name }}
  ports:
    - name: websocket
      port: {{ .Values.dbUI.port }}
      targetPort: websocket
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.dbUI.name }}-route
  namespace: {{ .Values.namespace }}
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  host: {{ .Values.dbUI.name }}.{{ .Values.routes.domain }}
  to:
    kind: Service
    name: {{ .Values.dbUI.name }}-service
  port:
    targetPort: websocket
  tls:
    termination: edge
